#%RAML 1.0 Library
usage: this uses for common datatypes
types:
  type: object
  datatype:
    properties:
      code:
        type: integer
        required: true

      status:
        type: string
        required: false

      message:
        type: string
        required: false






