#%RAML 1.0 DataType
type: object
properties:
          name:
            type: string
            required: false
            example: "rahwa"
          id:
            type: integer
            required: true
            example: 4
       